apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
    pipeline: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
      pipeline: gitlab
  template:
    metadata:
      labels:
        app: app-b
        pipeline: gitlab
    spec:
      containers:
      - name: app-b
        image: app-b:latest
        ports:
        - containerPort: 5001
        resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "150Mi"
              cpu: "250m"


---
apiVersion: v1
kind: Service
metadata:
  name: app-b-service
spec:
  selector:
    app: app-b
    pipeline: gitlab
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
