apiVersion: apps/v1
kind: Deployment
metadata:
  name: appa
  labels:
    app.kubernetes.io/name: python-app
    pipeline: github
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
      pipeline: github
      app: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
        pipeline: github
        app: python-app
    spec:
      containers:
        - name: application
          image: hayataf/projet-un:6e2ba87
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"