apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet1-app
  labels:
    app.kubernetes.io/name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
        - name: application
          image: hayataf/projet-un
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"