apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-python
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/fhayata/Projet-un.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      selfHeal: true
      prune: true